"""Demo composer: gameplay video with the live compute overlay.

Captures frames + per-decision depth during an eval run, then renders an
mp4: game frame, right panel with per-pathway router probabilities, the
charged compute, mode, value and action, and — on deliberative frames —
a post-hoc scene description generated by the same backbone (labelled as
such; the policy's action comes from the heads, not generated text).

Offline rendering so no live system is needed.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import torch

from reflexrl.envs.vizdoom_env import VizdoomPixelsEnv

MODE_NAMES = ["SPINAL", "REFLEX", "FAST", "DEEP"]
ACTION_NAMES = ["IDLE", "TURN_L", "TURN_R", "SHOOT", "L+SHOOT", "R+SHOOT"]
PANEL_W = 260
THOUGHT_H = 40


def record_rollout(agent, n_steps: int = 300, seed: int = 40_000,
                   env_kwargs: dict | None = None) -> list[dict]:
    """Frames + per-step decision record, greedy router policy."""
    env = VizdoomPixelsEnv(**(env_kwargs or {}))
    obs, _ = env.reset(seed=seed)
    rows = []
    for _ in range(n_steps):
        with torch.no_grad():
            out = agent.act(obs[None], greedy=True)
        d = int(out["depth"][0])
        a = int(out["action"][0])
        probs = torch.softmax(out["d_logits"], -1)[0].cpu().numpy().tolist()
        v = float(out["value"][0])
        obs, r, term, trunc, _ = env.step(a)
        rows.append({"frame": obs[-1].copy(), "depth": d, "action": a,
                     "reward": r, "done": term or trunc,
                     "probs": probs, "value": v})
        if term or trunc:
            obs, _ = env.reset()
    env.close()
    return rows


def add_thoughts(backbone, rows: list[dict], deepest: int,
                 max_captions: int = 24, prompt: str | None = None) -> list[dict]:
    """Post-hoc scene descriptions on deliberative frames.

    Only frames where the router chose the deepest pathway get a caption —
    the contrast (reflex frames have no words, deliberative frames do) is
    the point. Captions are generated by the same backbone after the fact
    and are labelled as post-hoc in the video.
    """
    idxs = [i for i, r in enumerate(rows) if r["depth"] == deepest]
    if len(idxs) > max_captions:
        keep = set(np.linspace(0, len(idxs) - 1, max_captions).astype(int).tolist())
        idxs = [i for k, i in enumerate(idxs) if k in keep]
    for i in idxs:
        rows[i]["thought"] = backbone.describe(rows[i]["frame"], prompt=prompt)
    return rows


def _fmt_cost(frac: float) -> str:
    return f"{frac * 100:.3f}%" if frac < 0.1 else f"{frac * 100:.1f}%"


def _panel(row: dict, cost_vector, mode_names: list[str], frame_h: int) -> np.ndarray:
    import cv2

    img = np.full((frame_h, PANEL_W, 3), 18, np.uint8)
    cv2.putText(img, "REFLEXRL", (16, 28), cv2.FONT_HERSHEY_SIMPLEX, 0.7,
                (235, 235, 235), 2)
    probs = row["probs"]
    y = 48
    for i, name in enumerate(mode_names):
        p = probs[i] if i < len(probs) else 0.0
        col = (90, 200, 255) if i == row["depth"] else (110, 110, 110)
        cv2.putText(img, f"{name:6s}", (16, y), cv2.FONT_HERSHEY_SIMPLEX,
                    0.42, col, 1)
        bw = int(130 * p)
        cv2.rectangle(img, (84, y - 9), (214, y + 2), (50, 50, 50), -1)
        cv2.rectangle(img, (84, y - 9), (84 + bw, y + 2), col, -1)
        cv2.putText(img, f"{p:4.2f}", (218, y), cv2.FONT_HERSHEY_SIMPLEX,
                    0.34, col, 1)
        y += 17
    cv2.putText(img, f"MODE {mode_names[row['depth']]}",
                (16, y + 12), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (90, 200, 255), 1)
    cv2.putText(img, f"COMPUTE {_fmt_cost(cost_vector[row['depth']])}",
                (16, y + 34), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (60, 200, 90), 1)
    cv2.putText(img,
                f"V {row['value']:+.2f}  ACT {ACTION_NAMES[row['action']]}",
                (16, y + 56), cv2.FONT_HERSHEY_SIMPLEX, 0.45,
                (200, 200, 200), 1)
    return img


def _thought_band(row: dict, w: int) -> np.ndarray:
    import cv2

    band = np.full((THOUGHT_H, w, 3), 12, np.uint8)
    if row.get("thought"):
        cv2.putText(band, f"\"{row['thought']}\"", (10, 26),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (60, 220, 255), 1)
    return band


def write_trace(rows: list[dict], path: str | Path):
    """JSONL decision trace: the written record behind the video."""
    with open(path, "w") as f:
        for i, r in enumerate(rows):
            f.write(json.dumps({
                "step": i, "depth": r["depth"], "action": r["action"],
                "reward": r["reward"], "probs": r["probs"],
                "value": r["value"], "done": r["done"],
                "thought": r.get("thought"),
            }) + "\n")


def compose_video(rows: list[dict], out_path: str | Path, cost_vector,
                  mode_names: list[str] | None = None, fps: int = 18):
    import cv2

    out_path = Path(out_path)
    n_pw = len(rows[0]["probs"])
    names = mode_names or MODE_NAMES[-n_pw:]
    h, w = rows[0]["frame"].shape[:2]
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    vw = cv2.VideoWriter(str(out_path), fourcc, fps, (w + PANEL_W, h + THOUGHT_H))
    for row in rows:
        frame = cv2.cvtColor(row["frame"], cv2.COLOR_RGB2BGR)
        panel = _panel(row, cost_vector, names, h)
        band = _thought_band(row, w + PANEL_W)
        vw.write(np.concatenate(
            [np.concatenate([frame, panel], axis=1), band], axis=0))
    vw.release()
    return out_path
